lin.xpl: SkyTrackReminder.c
	gcc -Wall -O2 -fPIC -fvisibility=hidden -ISDK/CHeaders/XPLM -DLIN -DXPLM200 -DXPLM210 -DXPLM300 -o SkyTrackReminder.o -c SkyTrackReminder.c
	gcc -shared -Wl, --version-script=exports.txt -o lin.xpl SkyTrackReminder.o
